# Generated by Django 4.2.3 on 2023-08-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Men', 'MEN'), ('Women', 'WOMEN'), ('Мужчина', 'МУЖЧИНА'), ('Женщина', 'ЖЕНЩИНА')], default='MEN', max_length=7, verbose_name='Пол'),
        ),
    ]
