# Generated by Django 4.2.3 on 2023-08-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default='MEN', max_length=7, verbose_name='Пол'),
        ),
    ]
