# Generated by Django 4.2.3 on 2024-02-26 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Количество баллов')),
            ],
            options={
                'verbose_name_plural': '[8] Ответы',
            },
        ),
        migrations.CreateModel(
            name='AnswerForQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '[9] Ответы на вопросы',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя автора')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия автора')),
            ],
            options={
                'verbose_name_plural': '[12] Авторы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание категории')),
                ('queue', models.IntegerField(verbose_name='Порядок')),
                ('status', models.CharField(choices=[('черновик', 'черновик'), ('опубликовано', 'опубликовано')], default='опубликовано', max_length=12, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': '[1] Категории',
            },
        ),
        migrations.CreateModel(
            name='PatternAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('answer_img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
                ('queue', models.IntegerField(verbose_name='Порядок')),
                ('status', models.CharField(choices=[('черновик', 'черновик'), ('опубликовано', 'опубликовано')], default='опубликовано', max_length=12, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': '[6] Шаблоны ответов',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вопроса')),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
                ('type_question', models.BooleanField(default=True, verbose_name='Тип вопроса (Ед.выб/Мн.выб : 1/0)')),
                ('obligatory', models.BooleanField(verbose_name='Обязательный ?')),
                ('queue', models.IntegerField(verbose_name='Порядок')),
                ('status', models.CharField(choices=[('черновик', 'черновик'), ('опубликовано', 'опубликовано')], default='опубликовано', max_length=12, verbose_name='Статус')),
                ('answer', models.ManyToManyField(to='api.patternanswer')),
            ],
            options={
                'verbose_name_plural': '[5] Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('черновик', 'черновик'), ('опубликовано', 'опубликовано')], default='опубликовано', max_length=12, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': '[7] Шкала',
            },
        ),
        migrations.CreateModel(
            name='SeoScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Ключ')),
                ('name', models.CharField(help_text='255 символов', max_length=255, verbose_name='Описание')),
                ('title', models.CharField(blank=True, help_text='255 символов', max_length=255, null=True)),
                ('description', models.CharField(blank=True, help_text='255 символов', max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, help_text='255 символов', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '[13] Шаблоны для метатегов',
            },
        ),
        migrations.CreateModel(
            name='Subtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название субтеста')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание до прохождения')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий преподавателя')),
                ('record_time', models.BooleanField(verbose_name='Запись времени прохождения')),
                ('time_for_solution', models.IntegerField(verbose_name='Время для прохождения')),
                ('mix_question', models.BooleanField(verbose_name='Перемешивать вопросы?')),
                ('queue', models.IntegerField(verbose_name='Порядок')),
                ('status', models.CharField(choices=[('черновик', 'черновик'), ('опубликовано', 'опубликовано')], default='опубликовано', max_length=12, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': '[4] Субтесты',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название теста')),
                ('description_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание до прохождения')),
                ('description_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание после прохождения')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий преподавателя')),
                ('record_time', models.BooleanField(verbose_name='Запись времени прохождения')),
                ('time_for_solution', models.IntegerField(verbose_name='Время для прохождения')),
                ('queue', models.IntegerField(verbose_name='Порядок')),
                ('status', models.CharField(choices=[('черновик', 'черновик'), ('опубликовано', 'опубликовано')], default='опубликовано', max_length=12, verbose_name='Статус')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='api.author', verbose_name='Автор')),
                ('category', models.ManyToManyField(related_name='category', to='api.category')),
            ],
            options={
                'verbose_name_plural': '[3] Тесты',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название темы')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание темы')),
                ('queue', models.IntegerField(verbose_name='Порядок')),
                ('status', models.CharField(choices=[('черновик', 'черновик'), ('опубликовано', 'опубликовано')], default='опубликовано', max_length=12, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': '[2] Темы',
            },
        ),
        migrations.CreateModel(
            name='TestSubtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subtest')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.ManyToManyField(related_name='topic', to='api.topic'),
        ),
        migrations.CreateModel(
            name='SubtestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('subtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subtest')),
            ],
        ),
        migrations.AddField(
            model_name='subtest',
            name='question',
            field=models.ManyToManyField(related_name='subtest_question', through='api.SubtestQuestion', to='api.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='subtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='api.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='question',
            name='subtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.subtest', verbose_name='Субтест'),
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('start_score', models.IntegerField(verbose_name='Кол-во баллов от')),
                ('finish_score', models.IntegerField(verbose_name='Кол-во баллов до')),
                ('description', models.TextField(null=True, verbose_name='Текст интерпретации')),
                ('queue', models.IntegerField(verbose_name='Порядок')),
                ('status', models.CharField(choices=[('черновик', 'черновик'), ('опубликовано', 'опубликовано')], default='опубликовано', max_length=12, verbose_name='Статус')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretationScale', to='api.scale', verbose_name='Шкала')),
            ],
            options={
                'verbose_name_plural': '[10] Интерпретации',
            },
        ),
        migrations.CreateModel(
            name='Attemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(null=True, verbose_name='Ответы пользователя')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attemptTest', to='api.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name_plural': '[11] Попытки',
            },
        ),
    ]
