# Generated by Django 4.2.7 on 2023-11-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attemption',
            old_name='answer',
            new_name='answers',
        ),
    ]
