# Generated by Django 4.2.3 on 2023-11-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attemption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий для преподавателя'),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='fdescription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание после'),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='sdescription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание до'),
        ),
        migrations.AlterField(
            model_name='test',
            name='fdescription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание после'),
        ),
        migrations.AlterField(
            model_name='test',
            name='sdescription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание до'),
        ),
    ]
