# Generated by Django 4.2.3 on 2023-11-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subtest_comment_alter_subtest_fdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type_question',
        ),
    ]
