# Generated by Django 4.2.3 on 2023-11-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_question_type_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.BooleanField(default=True, verbose_name='Тип вопроса (Ед.выб/Мн.выб-1/0)'),
        ),
    ]
