# Generated by Django 4.2.3 on 2023-11-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_type_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', verbose_name='Статус вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.BooleanField(default=True, verbose_name='Тип вопроса (Ед.выб/Мн.выб : 1/0)'),
        ),
    ]
