# Generated by Django 4.2.3 on 2023-11-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_answer_status_alter_question_type_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemption',
            name='answer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.answer'),
        ),
        migrations.AddField(
            model_name='attemption',
            name='subtest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.subtest'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Опубликовано', verbose_name='Статус вопроса'),
        ),
    ]
