# Generated by Django 4.2.7 on 2023-11-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_attemption_answer_attemption_subtest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemption',
            name='test',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.test'),
        ),
    ]
