# Generated by Django 4.2.7 on 2023-11-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_attemption_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemption',
            name='answer',
        ),
        migrations.AddField(
            model_name='attemption',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='answer', to='api.answer', verbose_name='Ответы теста'),
        ),
    ]
