# Generated by Django 4.2.3 on 2023-08-16 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('queue', models.IntegerField(verbose_name='Порядок следования ответа')),
                ('right', models.BooleanField(verbose_name='Ответ верный?')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='AnswerScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('description_1', models.TextField(verbose_name='Описание до')),
                ('description_2', models.TextField(verbose_name='Описание после')),
                ('comment', models.TextField(verbose_name='Комментарий для преподавателя')),
                ('time_for_solution', models.BooleanField(verbose_name='Записывать время прохождения?')),
                ('necessary_time', models.IntegerField(verbose_name='Необходимое для решения время')),
                ('mix_question', models.BooleanField(verbose_name='Перемешивать вопросы?')),
                ('status', models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', max_length=12, verbose_name='Статус теста')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название субтеста')),
                ('queue', models.IntegerField(verbose_name='Порядок следования субтеста')),
                ('description_1', models.TextField(verbose_name='Описание до')),
                ('description_2', models.TextField(verbose_name='Описание после')),
                ('comment', models.TextField(verbose_name='Комментарий для преподавателя')),
                ('time_for_solution', models.BooleanField(verbose_name='Записывать время прохождения?')),
                ('necessary_time', models.IntegerField(verbose_name='Необходимое для решения время')),
                ('mix_question', models.BooleanField(verbose_name='Перемешивать вопросы?')),
                ('status', models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', verbose_name='Статус субтеста')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtests', to='api.test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('queue', models.IntegerField(verbose_name='Порядок следования шкалы')),
                ('score', models.IntegerField(verbose_name='Количество баллов')),
                ('status', models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', verbose_name='Статус шкалы')),
                ('answer', models.ManyToManyField(related_name='scale_answer', through='api.AnswerScale', to='api.answer', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Шкала',
                'verbose_name_plural': 'Шкалы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вопроса')),
                ('queue', models.IntegerField(verbose_name='Порядок следования вопроса')),
                ('type_question', models.CharField(choices=[('Единственный выбор', 'Единственный выбор'), ('Множественный выбор', 'Множественный выбор')], default='Единственный выбор', max_length=19, verbose_name='Тип вопроса')),
                ('obligatory', models.BooleanField(verbose_name='Обязательный ?')),
                ('mix_question', models.BooleanField(verbose_name='Перемешивать вопросы?')),
                ('status', models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', verbose_name='Статус вопроса')),
                ('subtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.subtest', verbose_name='Субтест')),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название интерпретации')),
                ('queue', models.IntegerField(verbose_name='Порядок следования интерпретации')),
                ('text', models.TextField(verbose_name='Текст')),
                ('start_score', models.IntegerField(verbose_name='Количество баллов от')),
                ('finish_score', models.IntegerField(verbose_name='Количество баллов до')),
                ('status', models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', verbose_name='Статус интерпретации')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scale')),
            ],
        ),
        migrations.CreateModel(
            name='Attemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Номер попытки')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answerscale',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scale'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.question', verbose_name='Вопрос'),
        ),
        migrations.AlterUniqueTogether(
            name='answerscale',
            unique_together={('answer', 'scale')},
        ),
    ]
