# Generated by Django 4.2.3 on 2023-07-23 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ответа')),
                ('queue', models.IntegerField(verbose_name='Порядок следования ответа')),
                ('description', models.CharField(max_length=255, verbose_name='Описание ответа')),
                ('score', models.IntegerField(verbose_name='Количество баллов')),
                ('right', models.BooleanField(verbose_name='Ответ верный?')),
                ('status', models.CharField(max_length=255, verbose_name='Статус ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('description_1', models.CharField(max_length=255, verbose_name='Описание до')),
                ('description_2', models.CharField(max_length=255, verbose_name='Описание после')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий для преподавателя')),
                ('time_for_solution', models.BooleanField(verbose_name='Записывать время прохождения?')),
                ('necessary_time', models.IntegerField(verbose_name='Необходимое для решения время')),
                ('mix_question', models.BooleanField(verbose_name='Перемешивать вопросы?')),
                ('status', models.CharField(max_length=255, verbose_name='Статус теста')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название субтеста')),
                ('queue', models.IntegerField(verbose_name='Порядок следования субтеста')),
                ('description_1', models.CharField(max_length=255, verbose_name='Описание до')),
                ('description_2', models.CharField(max_length=255, verbose_name='Описание после')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий для преподавателя')),
                ('time_for_solution', models.BooleanField(verbose_name='Записывать время прохождения?')),
                ('necessary_time', models.IntegerField(verbose_name='Необходимое для решения время')),
                ('mix_question', models.BooleanField(verbose_name='Перемешивать вопросы?')),
                ('status', models.CharField(max_length=255, verbose_name='Статус теста')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
        ),
        migrations.CreateModel(
            name='Scales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шкалы')),
                ('queue', models.IntegerField(verbose_name='Порядок следования шкалы')),
                ('description', models.CharField(max_length=255, verbose_name='Описание шкалы')),
                ('status', models.CharField(max_length=255, verbose_name='Статус шкалы')),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answers')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вопроса')),
                ('queue', models.IntegerField(verbose_name='Порядок следования вопроса')),
                ('type_question', models.CharField(max_length=255, verbose_name='Тип вопроса')),
                ('obligatory', models.BooleanField(verbose_name='Обязательный ?')),
                ('mix_question', models.BooleanField(verbose_name='Перемешивать вопросы?')),
                ('status', models.CharField(max_length=255, verbose_name='Статус вопроса')),
                ('subtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subtest')),
            ],
        ),
        migrations.CreateModel(
            name='Interpretations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название интерпретации')),
                ('queue', models.IntegerField(verbose_name='Порядок следования интерпретации')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('start_score', models.IntegerField(verbose_name='Количество баллов от')),
                ('finish_score', models.IntegerField(verbose_name='Количество баллов до')),
                ('status', models.CharField(max_length=255, verbose_name='Статус интерпретации')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scales')),
            ],
        ),
        migrations.CreateModel(
            name='Attemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер попытки')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата и время прохождения')),
                ('time_spent', models.IntegerField(verbose_name='Затраченное время')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.answers')),
                ('interpretation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.interpretations')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.questions')),
                ('scale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.scales')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questions'),
        ),
    ]
