# Generated by Django 4.2.3 on 2023-08-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': '5) Ответы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1) Категории'},
        ),
        migrations.AlterModelOptions(
            name='interpretation',
            options={'verbose_name_plural': '8) Интерпретации'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '4) Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={'verbose_name': 'Шкала', 'verbose_name_plural': '6) Шкалы'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Балл', 'verbose_name_plural': '7) Баллы'},
        ),
        migrations.AlterModelOptions(
            name='subtest',
            options={'verbose_name_plural': '3) Субтесты'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': '2) Тесты'},
        ),
        migrations.AddField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
