# Generated by Django 4.2.3 on 2023-08-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerscale',
            unique_together={('answer', 'scale')},
        ),
        migrations.RemoveField(
            model_name='answerscale',
            name='score',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
