# Generated by Django 4.2.3 on 2023-07-24 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemption',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.questions', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='answers',
            name='scales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scales'),
        ),
    ]
