# Generated by Django 4.2.3 on 2023-07-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.IntegerField(default=0, verbose_name='Пользователь'),
        ),
    ]
