# Generated by Django 4.2.3 on 2023-10-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_test_subtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subtest',
            field=models.ManyToManyField(related_name='test_subtest', through='api.TestSubtest', to='api.subtest', verbose_name='СубТест'),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='api.test', verbose_name='Тест'),
        ),
    ]
