# Generated by Django 4.2.3 on 2023-08-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
