# Generated by Django 4.2.3 on 2023-07-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
    ]
