# Generated by Django 4.2.3 on 2023-08-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_answerscale_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Количество баллов')),
                ('answer', models.ManyToManyField(related_name='score_answer', through='api.AnswerScale', to='api.answer', verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'Балл',
                'verbose_name_plural': '[7] Баллы',
            },
        ),
        migrations.AlterUniqueTogether(
            name='answerscale',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answerscale',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.score'),
        ),
        migrations.AlterUniqueTogether(
            name='answerscale',
            unique_together={('answer', 'scale', 'score')},
        ),
    ]
