# Generated by Django 4.2.3 on 2023-10-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_subtest_description_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.BooleanField(verbose_name='Тип вопроса (Един. выб/Множ. выб - 1/0)'),
        ),
    ]
