# Generated by Django 4.2.3 on 2023-08-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_score_alter_answerscale_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='queue',
            field=models.IntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='queue',
            field=models.IntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='queue',
            field=models.IntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='queue',
            field=models.IntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='queue',
            field=models.IntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='queue',
            field=models.IntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='test',
            name='queue',
            field=models.IntegerField(verbose_name='Порядок'),
        ),
    ]
