# Generated by Django 4.2.3 on 2023-07-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_test_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='number',
        ),
    ]
