# Generated by Django 4.2.3 on 2023-08-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subtestquestion_subtest_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleInterpret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.interpretation')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scale')),
            ],
            options={
                'unique_together': {('scale', 'interpret')},
            },
        ),
    ]
