# Generated by Django 4.2.3 on 2023-08-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_test_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Interpretations',
            new_name='Interpretation',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Scales',
            new_name='Scale',
        ),
    ]
