# Generated by Django 4.2.3 on 2023-08-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_scaleinterpret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretation',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='api.scale', verbose_name='Шкала'),
        ),
    ]
