# Generated by Django 4.2.3 on 2023-08-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_answers_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtests', to='api.test', verbose_name='Тест'),
        ),
    ]
