# Generated by Django 4.2.3 on 2023-08-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_answer_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
