# Generated by Django 4.2.3 on 2023-08-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_interpretation_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', max_length=12, verbose_name='Статус вопроса'),
        ),
    ]
