# Generated by Django 4.2.3 on 2023-08-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_subtest_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', verbose_name='Статус ответа'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', verbose_name='Статус интерпретации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', verbose_name='Статус вопроса'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', verbose_name='Статус шкалы'),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', verbose_name='Статус субтеста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Черновик', max_length=12, verbose_name='Статус теста'),
        ),
    ]
