# Generated by Django 4.2.3 on 2023-08-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_answer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='mix_question',
        ),
    ]
