# Generated by Django 4.2.3 on 2023-08-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_test_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], default='Опубликовано', max_length=12, verbose_name='Статус вопроса'),
        ),
    ]
