# Generated by Django 4.2.3 on 2023-08-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_answer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Ответ', 'verbose_name_plural': '[5] Ответы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '[1] Категории'},
        ),
        migrations.AlterModelOptions(
            name='interpretation',
            options={'verbose_name_plural': '[8] Интерпретации'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '[4] Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={'verbose_name': 'Шкала', 'verbose_name_plural': '[6] Шкалы'},
        ),
        migrations.AlterModelOptions(
            name='subtest',
            options={'verbose_name_plural': '[3] Субтесты'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['id'], 'verbose_name_plural': '[2] Тесты'},
        ),
        migrations.AlterUniqueTogether(
            name='answerscale',
            unique_together={('answer', 'scale')},
        ),
        migrations.RemoveField(
            model_name='answerscale',
            name='score',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
